### ISSUE TITLE
Training Doesn't Start When Using Multiple GPUs on AWS EC2

### ISSUE THREAD

**Issue by mossadhelalitalentbait** [ThilinaRajapakse/simpletransformers#742]
Thank you very much for the great work and the support you are providing.
I ran into the following issue:

**Describe the bug**
After the model pre-processes the input and is about to start training/fine-tuning, the process freezes or appears to be stuck. This happens only when using multiple GPUs (i.e. setting `n_gpu` to 1 works normally).

**Screenshots**
![Screenshot](https://i.imgur.com/lJSyR9c.png "Screenshot")

**Additional Info**
I am not sure whether this is relevant, the freeze happens when I try using 3 or 4 GPUs. If I specify `n_gpu` to 2, the code crashes with this error:
```
  File "/job-posting-classifier/model/job_posting_classifier.py", line 69, in train_model
    acc=accuracy_score)
  File "/opt/conda/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 306, in train_model
    **kwargs,
  File "/opt/conda/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 474, in train
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 726, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 160, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 22, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/comm.py", line 56, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 2: unhandled system error
```

**Configuration:**
I am using an AWS EC2 server with 4 Tesla T4 GPUs (g4dn.12xlarge). The code runs inside a docker container (`nvcr.io/nvidia/pytorch:20.08-py3`). The used model is `distilbert-base-german-cased`
- OS: Ubuntu 20.04.1 LTS
- Nvidia Driver Version: 450.66
- Cuda Version: 11.0
- simpletransformers==0.47.3
- python==3.6.10
- torch version: 1.7.0a0+8deb4fe

Would appreciate your feedback. Thanks.

**Comment by mossadhelalitalentbait** [comment]
I am sorry the issue turned out to be related to Multi-GPU + Docker not the library. 
For those who run into the same issue, [this](https://github.com/NVIDIA/nccl/issues/290) fixed it for me.

You need to mount the `dev/shm` from the host to the container.
