### ISSUE TITLE
LanguageModelingModel not using GPU 

### ISSUE THREAD

**Issue by gdet** [ThilinaRajapakse/simpletransformers#757]
Hello,

I have four GPU NVIDIA GV102. I have created a simpletransformers environment, I have installed pytorch and cuda but when I try to run the model I get memory error and I can see that GPUs are not used at all. If I use print(device_lib.list_local_devices()) I can see all four GPUs.

I tried like this:

     model = LanguageModelingModel(
         "gpt2", None, args=model_args, train_files=train_file,use_cuda=True
     )

also 

    model = LanguageModelingModel(
         "gpt2", None, args=model_args, train_files=train_file,use_cuda=True, cuda_device="1"
    )

I have also added this in model_args:  "n_gpu": 2,

When I use  watch -n 4 nvidia-smi I get this:

     +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  GeForce RTX 208...  Off  | 00000000:21:00.0 Off |                  N/A |
    | 27%   41C    P8     1W / 260W |    312MiB / 11019MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
    |   1  GeForce RTX 208...  Off  | 00000000:44:00.0 Off |                  N/A |
    | 28%   42C    P8    14W / 260W |    312MiB / 11019MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
    |   2  GeForce RTX 208...  Off  | 00000000:62:00.0 Off |                  N/A |
    | 27%   40C    P8     8W / 260W |    312MiB / 11019MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
    |   3  GeForce RTX 208...  Off  | 00000000:63:00.0 Off |                  N/A |
    | 27%   42C    P8    13W / 260W |    312MiB / 11019MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+

    +-----------------------------------------------------------------------------+
    | Processes:                                                       GPU Memory |
    |  GPU       PID   Type   Process name                             Usage      |
    |=============================================================================|
    |    0     33568      C   python                                       301MiB |
    |    1     33568      C   python                                       301MiB |
    |    2     33568      C   python                                       301MiB |
    |    3     33568      C   python                                       301MiB |
    +-----------------------------------------------------------------------------+ ``

Thank you

and when the program reaches  model.train_model(train_file, eval_file=test_file)

I get this error 

    INFO:simpletransformers.language_modeling.language_modeling_utils: Creating features from dataset file at cache_dir/
    Traceback (most recent call last):
     File "run.py", line 49, in <module>
       model.train_model(train_file, eval_file=test_file)
      File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/site- 
     packages/simpletransformers/language_modeling/language_modeling_model.py", line 360, in train_model
       train_dataset = self.load_and_cache_examples(train_file, verbose=verbose)
     File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/site- 
      packages/simpletransformers/language_modeling/language_modeling_model.py", line 918, in load_and_cache_examples
      return SimpleDataset(
     File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/site- 
     packages/simpletransformers/language_modeling/language_modeling_utils.py", line 100, in __init__
       (tokenizer, line) for line in f.read().splitlines() if (len(line) > 0 and not line.isspace())
      File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/codecs.py", line 322, in decode
       (result, consumed) = self._buffer_decode(data, self.errors, final)
      MemoryError
     INFO:wandb.internal.internal:Internal process exited

**Comment by ThilinaRajapakse** [comment]
A few points here;

- If you are using multiple GPUs, don't specify a `cuda_device`. That is for when you have multiple GPUs, but only want to use one of them.
- `cuda_device` expects an integer and not a string.
- It might be better to use distributed training for language modeling. More info [here](https://simpletransformers.ai/docs/lm-specifics/#distributed-training).

**Comment by gdet** [comment]
Thank you for your help.
I have removed cuda_device and I used distributed training example. Now I get this error in train.txt

    INFO:simpletransformers.language_modeling.language_modeling_model: Training of None tokenizer complete. Saved to     outputs/from_scratch_.
    /home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/site-packages/transformers/tokenization_utils_base.py:1322:     FutureWarning: The `max_len` attribute has been deprecated and will be removed in a future version, use `model_max_length`     instead.
      warnings.warn(
    INFO:simpletransformers.language_modeling.language_modeling_model: Training language model from scratch
    beofre train model
    INFO:simpletransformers.language_modeling.language_modeling_utils: Creating features from dataset file at cache_dir/
    INFO:simpletransformers.language_modeling.language_modeling_utils: File: data/train.txt
    Traceback (most recent call last):
      File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in     <module>
        main()
      File "/home/hatzimin/.conda/envs/simpletransformers/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in     main
        raise subprocess.CalledProcessError(returncode=process.returncode,
    subprocess.CalledProcessError: Command '['/home/hatzimin/.conda/envs/simpletransformers/bin/python3', '-u', 'train_lm.py', '--local_rank=2']' died with <Signals.SIGKILL: 9>.

It crashes in 

    model.train_model(
       train_file, eval_file=test_file,
    )

Also if I use top and watch -n 4 nvidia-smi

At start the CPU is only used and everything in GPU is zero:

     PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND

     79333 hatzimin  20   0 20,816g 1,440g 249420 S 485,7  2,3   9:50.07 python3
     79331 hatzimin  20   0 20,887g 1,443g 251056 S 423,8  2,3  10:14.08 python3
     79332 hatzimin  20   0 20,816g 1,445g 251520 S 361,9  2,3   9:53.13 python3

In train_model the GPU starts showing this after "compute merges":

       +-----------------------------------------------------------------------------+
       | NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
       |-------------------------------+----------------------+----------------------+
       | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
       | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
       |===============================+======================+======================|
       |   0  GeForce RTX 208...  Off  | 00000000:21:00.0 Off |                  N/A |
       | 27%   39C    P8     1W / 260W |     11MiB / 11019MiB |      0%      Default |
       +-------------------------------+----------------------+----------------------+
       |   1  GeForce RTX 208...  Off  | 00000000:44:00.0 Off |                  N/A |
       | 27%   43C    P2    55W / 260W |   1216MiB / 11019MiB |      5%      Default |
       +-------------------------------+----------------------+----------------------+
       |   2  GeForce RTX 208...  Off  | 00000000:62:00.0 Off |                  N/A |
       | 27%   39C    P8     8W / 260W |     11MiB / 11019MiB |      0%      Default |
       +-------------------------------+----------------------+----------------------+
       |   3  GeForce RTX 208...  Off  | 00000000:63:00.0 Off |                  N/A |
       | 27%   40C    P8    13W / 260W |     11MiB / 11019MiB |      0%      Default |
       +-------------------------------+----------------------+----------------------+

       +-----------------------------------------------------------------------------+
       | Processes:                                                       GPU Memory |
       |  GPU       PID   Type   Process name                             Usage      |
       |=============================================================================|
       |    0     79331      C   ...nda/envs/simpletransformers/bin/python3  1205MiB |
       |    1     79332      C   ...nda/envs/simpletransformers/bin/python3  1205MiB |
       +-----------------------------------------------------------------------------+

Is that normal? Also what else could I do to fix memory error. After Signal SIGKILL I run dmesg and I can see this error:

    [4828811.086861] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0-1,global_oom,task_memcg=/user.slice,task=python3,pid=79331,uid=1005
    [4828811.086936] Out of memory: Killed process 79331 (python3) total-vm:85663880kB, anon-rss:63639632kB, file-rss:71768kB, shmem-rss:10240kB, UID:1005 pgtables:128624kB oom_score_adj:0
[4828813.366428] oom_reaper: reaped process 79331 (python3), now anon-rss:0kB, file-rss:74732kB, shmem-rss:10240kB

My memory is:

     total        used        free      shared  buff/cache   available
    Mem:          64273        8746       44776           6       10749       54870


Thank you

**Comment by ThilinaRajapakse** [comment]
It's normal for only the CPU to be used in the beginning. This is because the tokenizer training is handled by the CPU.

How large is your data file? Can you try running it with a smaller file to verify that the process is working?

**Comment by gdet** [comment]
My file is 29GB. I will try with a smaller file to check if the process is working and I will inform you. thank you

**Comment by gdet** [comment]
Hello again,

i managed to start the training with a file of 1GB but the training is running 5 days now.

this is some the messages 

        INFO:simpletransformers.language_modeling.language_modeling_model: Training started
        Epoch 1 of 20:   0%|                                                                                                                                                                                                        | 0/20 [00:00<?, ?it/s/home/.conda/envs/simpletransformers/lib/python3.8/site-packages/torch/optim  /lr_scheduler.py:231: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.07123 [01:28<132:31:41,  4.63it/s]
          warnings.warn("To get the last learning rate computed by the scheduler, "                                                                                                                        | 399/2207123 [01:27<127:58:29,  4.79it/s]
                                                                                                                                                                                                                                                           /home/.conda/envs/simpletransformers/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:200: UserWarning: Please also save or load the state of the optimzer when saving or loading the scheduler.3 [28:33<136:58:42,  4.46it/s]
          warnings.warn(SAVE_STATE_WARNING, UserWarning)                                                                                                                                                          | 7999/2207123 [28:32<132:40:45,  4.60it/s]
                                                                                                                                                                                                                                                        INFO:simpletransformers.language_modeling.language_modeling_utils: Creating features from dataset file at cache_dir/                                                                                      | 11999/2207123 [42:54<131:11:54,  4.65it/s]
        INFO:simpletransformers.language_modeling.language_modeling_utils: File: data/xaatestsmallsmall.txt                                                                                                      | 11999/2207123 [42:54<131:18:21,  4.64it/s]
        INFO:simpletransformers.language_modeling.language_modeling_utils: Creating features from dataset file at cache_dir/
        INFO:simpletransformers.language_modeling.language_modeling_utils: File: data/xaatestsmallsmall.txt
        INFO:simpletransformers.language_modeling.language_modeling_utils: Saving features into cached file         cache_dir/gpt2_cached_lm_507_xaatestsmallsmall.txt
        INFO:simpletransformers.language_modeling.language_modeling_utils: Saving features into cached file         cache_dir/gpt2_cached_lm_507_xaatestsmallsmall.txt
        INFO:simpletransformers.language_modeling.language_modeling_model:{'eval_loss': 4.501949772160908, 'perplexity': `tensor(90.1928)}`

but the percentage of epoch is not changing it is still 0%. And the latest message is : 

        NFO:simpletransformers.language_modeling.language_modeling_utils: Loading features from cached file cache_dir/gpt2_cached_lm_507_xaatestsmallsmall.txt                                       | 287999/2207123 [68:35:59<116:09:26,  4.59it/s]
        INFO:simpletransformers.language_modeling.language_modeling_utils: Loading features from cached file cache_dir/gpt2_cached_lm_507_xaatestsmallsmall.txt                                      | 287999/2207123 [68:35:59<116:15:43,  4.59it/s]
        INFO:simpletransformers.language_modeling.language_modeling_model:{'eval_loss': 2.592749223299814, 'perplexity': tensor(13.3665)}
        INFO:simpletransformers.language_modeling.language_modeling_model:{'eval_loss': 2.592749223299814, 'perplexity': tensor(13.3665)}


Is this normal?
Also if i cannot train more than 1GB how can I train the 38GB I have? My GPU is now working at 99%. Any suggestions would help.
Thank you

**Comment by ThilinaRajapakse** [comment]
Not sure why the epoch percentage isn't updating because it looks like the model is being trained.

I'm not sure you can process the full 38 GB at once if your system memory is 64 GB. You should be able to do more than 1 GB but I'm not sure how much. On a related note, if the training didn't complete in 5 days when using only 1 GB of data, I don't know if it will be practical to train on 38 GBs.

**Comment by gdet** [comment]
Ok thank you for your help. So If I cannot train all the 38GB at once what should be the steps for eventually using all the data?

**Comment by ThilinaRajapakse** [comment]
Right now, I don't think you can use all the data with Simple Transformers. You should be able to once Lazy Loading is implemented for Language Modeling (should be soon, but depends on when I'll have the time). However, that still won't help with the core problem of not having enough compute resources to train a GPT2 model from scratch. Unfortunately, the kind of compute resources required to train a GPT 2 model is out of reach for most people.
