### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by flydragon2018** [ThilinaRajapakse/simpletransformers#819]
**Describe the bug**
 
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in convert(t)
    608             if convert_to_format is not None and t.dim() == 4:
    609                 return t.to(device, dtype if t.is_floating_point() else None, non_blocking, memory_format=convert_to_format)
--> 610             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    611 
    612         return self._apply(convert)

RuntimeError: CUDA error: device-side assert triggered
**To Reproduce**
 run multi-class minimal example on google colab 
**Expected behavior**

normal behavior
**Screenshots**

**Desktop (please complete the following information):**
 - OS  google colab

**Additional context**

**Comment by kwanhong66** [comment]
I just ran multi-class minimal example code [Link](https://simpletransformers.ai/docs/multi-class-classification/) Google Colab and there was no error happened to you. Did you modify the code? (for example, labels)

**Comment by flydragon2018** [comment]
the minimal example no errors.
I just replace the miminal data with my own dataset, then the error pops up.
however I can run it on google colab without using cuda. however that is way too slow to finish training the model.

**Comment by flydragon2018** [comment]
BTW I can run it on my own computer with cuda. However I can only run one epoch and with small batch size, due to my hardware  constraint.

**Comment by flydragon2018** [comment]
perhaps google colab problem? or it is fixed?
Now I can run the same codes on google colab without error.

**Comment by ThilinaRajapakse** [comment]
No clue, but if it's fixed then all good. 😄

**Comment by ZephyrLiu** [comment]
I met same problem. I removed cache and outputs, and restarted runtime. Then the problem was solved.
